- name: Download and Deploy Single EAR to WebSphere
  hosts: 10.112.30.40
  become: yes

  vars:
    jenkins_user: your_user
    jenkins_token: your_token
    docker_container_name: "emmis-t6"
    wsadmin_path: "/opt/IBM/WebSphere/AppServer_Emmis/profiles/AppSrv01_eMMIS/bin/wsadmin.sh"
    ear_url: "http://mdcmwp-jenkins.mcd.ifox.loc:8080/job/eMMIS-DXCD/lastSuccessfulBuild/artifact/builds/medicaid_EAR6.ear"
    ear_dest_path: "/opt/WAS/ear/medicaid_EAR6.ear"

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "/opt/WAS/ear"
        state: directory
        mode: '0755'

    - name: Download EAR file from Jenkins
      get_url:
        url: "{{ ear_url }}"
        dest: "{{ ear_dest_path }}"
        url_username: "{{ jenkins_user }}"
        url_password: "{{ jenkins_token }}"
        force_basic_auth: yes
        mode: '0644'

    - name: Deploy EAR inside Docker container using wsadmin
      command: >
        docker exec {{ docker_container_name }}
        {{ wsadmin_path }}
        -lang jython -f /opt/WAS/scripts/deploy_was_script.py {{ ear_dest_path }}
