---
- name: Download EAR file from Jenkins to /tmp on Docker Host
  hosts: all
  become: yes
  tasks:
    - name: Download EAR file
      get_url:
        url: "http://mdcmwp-jenkins.mcd.ifox.loc:8080/view/eMMIS/job/eMMIS-DXCD/86/"
        dest: /tmp/medicaid_EAR6.ear
        mode: '0644'
