---
- name: Download EAR file from Jenkins to /tmp on Docker Host
  hosts: Docker02
  become: yes
  tasks:
    - name: Download EAR file
      get_url:
        url: "http://mdcmwp-jenkins.mcd.ifox.loc:8080/job/eMMIS-DXCD/lastSuccessfulBuild/artifact/builds/emmis.ear"
        dest: /tmp/medicaid_EAR6.ear
        mode: '0644'
