---
- name: Download EAR file from Jenkins to /tmp on Docker Host
  hosts: 10.112.30.40
  become: yes
  tasks:
    - name: Download EAR file
      get_url:
        url: "http://mdcmwp-jenkins.mcd.ifox.loc:8080/job/eMMIS-DXCD/lastSuccessfulBuild/"
        dest: /home/anandyala/medicaid_EAR6.ear
        url_username: "{{ jenkins_user }}"
        url_password: "{{ jenkins_token }}"
        force_basic_auth: yes
        mode: '0644'
