- name: Download and Deploy EARs to WebSphere
  hosts: 10.112.30.40
  become: yes

  vars:
    jenkins_user: "{{ jenkins_user }}"
    jenkins_token: "{{ jenkins_token }}"
    ear_dest_dir: "/home/anandyala/WAS/ear"

    ear_downloads:
      - url: "http://mdcmwp-jenkins.mcd.ifox.loc:8080/job/eMMIS-DXCD/lastSuccessfulBuild/artifact/masterBuild/artifacts/medicaid_EAR6.ear"
        dest: "{{ ear_dest_dir }}/medicaid_EAR6.ear"
      - url: "http://mdcmwp-jenkins.mcd.ifox.loc:8080/job/eMMIS-DXCD/lastSuccessfulBuild/artifact/masterBuild/artifacts/medicaidSupplementsEAR.ear"
        dest: "{{ ear_dest_dir }}/medicaidSupplementsEAR.ear"

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ ear_dest_dir }}"
        state: directory
        mode: '0755'
        owner: anandyala
        group: anandyala

    - name: Download EAR files from Jenkins
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        url_username: "{{ jenkins_user }}"
        url_password: "{{ jenkins_token }}"
        force_basic_auth: yes
        mode: '0644'
      loop: "{{ ear_downloads }}"

    - name: Deploy medicaid_EAR6.ear inside Docker container using wsadmin
      command: >
        docker exec emmis-t6
        /opt/IBM/WebSphere/AppServer_Emmis/profiles/AppSrv01_eMMIS/bin/wsadmin.sh
        -lang jython
        -user "{{was_user}}}"
        -password "{{was_password}}"
        -f /home/anandyala/WAS/scripts/deploy_was_script.py
        {{ ear_dest_dir }}/medicaid_EAR6.ear

    - name: Deploy medicaidSupplementsEAR.ear inside Docker container using wsadmin
      command: >
        docker exec emmis-t6
        /opt/IBM/WebSphere/AppServer_Emmis/profiles/AppSrv01_eMMIS/bin/wsadmin.sh
        -lang jython
        -user "{{was_user}}}"
        -password "{{was_password}}"
        -f /home/anandyala/WAS/scripts/deploy_was_script.py
        {{ ear_dest_dir }}/medicaidSupplementsEAR.ear
