---
- name: Download EAR file from Jenkins to /tmp on Docker Host
  hosts: 10.112.30.40
  become: yes
  tasks:
    - name: Download EAR file
      get_url:
        url: "http://anandyala:11cee16aa7204b41b314196cea7f651910@mdcmwp-jenkins.mcd.ifox.loc:8080/job/eMMIS-DXCD/lastSuccessfulBuild/"
        dest: /home/anandyala/medicaid_EAR6.ear
        mode: '0644'
