- name: Test downloading EAR file from Jenkins
  hosts: 10.112.30.40
  vars:
    jenkins_user: your_user
    jenkins_token: your_token
    #test_url: "http://mdcmwp-jenkins.mcd.ifox.loc:8080/job/eMMIS-DXCD/lastSuccessfulBuild/"
    test_url: "http://mdcmwp-jenkins.mcd.ifox.loc:8080/view/eMMIS/job/eMMIS_Apr_June_Release/lastSuccessfulBuild/"
  tasks:
    - name: Try downloading one EAR
      get_url:
        url: "{{ test_url }}"
        dest: "/tmp/medicaid_EAR6.ear"
        url_username: "{{ jenkins_user }}"
        url_password: "{{ jenkins_token }}"
        force_basic_auth: yes
        mode: '0644'
