- name: Test downloading EAR file from Jenkins
  hosts: 10.112.30.40
  vars:
    jenkins_user: "{{ jenkins_user }}"
    jenkins_token: "{{ jenkins_token }}"
    ear_dest_dir: "/tmp/WAS/ear"

    ear_downloads:
      - url: "http://mdcmwp-jenkins.mcd.ifox.loc:8080/view/eMMIS/job/eMMIS_Apr_June_Release/lastSuccessfulBuild/artifact/masterBuild/artifacts/medicaid_EAR6.ear"
        dest: "{{ ear_dest_dir }}/medicaid_EAR6.ear"
      - url: "http://mdcmwp-jenkins.mcd.ifox.loc:8080/view/eMMIS/job/eMMIS_Apr_June_Release/lastSuccessfulBuild/artifact/masterBuild/artifacts/medicaidSupplementsEAR.ear"
        dest: "{{ ear_dest_dir }}/medicaidSupplementsEAR.ear"
  
  tasks:

    - name: Ensure EAR destination directory exists on host
      file:
        path: "{{ ear_dest_dir }}"
        state: directory
        mode: '0755'
        owner: anandyala
        group: anandyala

    - name: Download EAR files from Jenkins
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        url_username: "{{ jenkins_user }}"
        url_password: "{{ jenkins_token }}"
        force_basic_auth: yes
        force: yes
        mode: '0644'
      loop: "{{ ear_downloads }}"
