- name: Backup and Upgrade WAS & IHS in a Single Docker Container
  hosts: all
  become: yes

  vars:
    container_name: ""
    was_install_dir: ""
    was_profile_dir: ""
    was_repo_path: ""
    was_feature_id: ""

    ihs_install_dir: ""
    ihs_repo_path: ""
    ihs_feature_id: ""
    
    java_install_dir: ""
    java_repo_path: ""
    java_feature_id: ""

   # backup_dir: "/tmp/backup/{{ inventory_hostname }}/{{ ansible_date_time.date }}"

  tasks:
    #- name: Create backup directory on Docker host
    # file:
    #    path: "{{ backup_dir }}"
    #    state: directory
    
    - name: Stop the  WebSphere Application Server 
      shell: >
        docker exec {{ container_name }} /opt/IBM/WebSphere/AppServer_Emmis/profiles/AppSrv01_eMMIS/bin/stopServer.sh server1 -user {{was_user}} -password {{was_password}}
        
    - name: Stop the  HTTP Server 
      shell: >
        docker exec {{ container_name }} {{ ihs_install_dir }}/bin/apachectl stop

    
   # - name: List WebSphere Application Server Fix Packs inside container
   #   shell: >
   #     docker exec --user was {{ container_name }} /opt/IBM/InstallationManager/eclipse/tools/imcl listAvailablePackages
   #     -repositories {{ was_repo_path }}
        
    
   # - name: List HTTP Server Fix Packs inside container
   #   shell: >
   #     docker exec --user was {{ container_name }} /opt/IBM/InstallationManager/eclipse/tools/imcl listAvailablePackages
   #     -repositories {{ was_repo_path }}
        
    
   # - name: List Java Server Fix Packs inside container
   #   shell: >
   #     docker exec --user was {{ container_name }} /opt/IBM/InstallationManager/eclipse/tools/imcl listAvailablePackages 
   #     -repositories {{ was_repo_path }}
        
        
    - name: Upgrade WebSphere Application Server inside container
      shell: >
        docker exec --user was {{ container_name }} /opt/IBM/InstallationManager/eclipse/tools/imcl install {{ was_feature_id }}
        -repositories {{ was_repo_path }}
        -installationDirectory {{ was_install_dir }}
        -acceptLicense
        

    - name: Upgrade IBM HTTP Server inside container (as was)
      shell: >
        docker exec --user was {{ container_name }} /opt/IBM/InstallationManager/eclipse/tools/imcl install {{ ihs_feature_id }}
        -repositories {{ ihs_repo_path }}
        -installationDirectory {{ ihs_install_dir }}
        -acceptLicense
        

    - name: Upgrade Java 
      shell : >
        docker exec --user was {{ container_name }} /opt/IBM/InstallationManager/eclipse/tools/imcl install {{ java_feature_id }}
        -repositories {{ java_repo_path }}
        -installationDirectory {{ java_install_dir }}
        -acceptLicense
        
